Solution1/PresentationApp/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PresentationApp.Controllers
{
    public class SupportController : Controller
    {
      //  [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        
        [HttpGet] //role is to load the page
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost] //role is to receive data from a Form submission
        public ActionResult Contact(string email, string query)
        {
            //store in db or inform the person in charge

            if (string.IsNullOrEmpty(query) || string.IsNullOrEmpty(email))
            {
                ViewData["warning"] = "One of the inputs is left empty";
            }
            else
                ViewData["feedback"] = "Thanks for your query.  We will revert back with a reply very soon";
            
         
            return View();
        }


    }
}

Solution1/PresentationApp/Views/Shared/PartialFeedbackView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@




@if (TempData["feedback"] != null)
{
    <div class="alert alert-primary" role="alert">
        @TempData["feedback"]
    </div>
}

@if (TempData["warning"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["warning"]
    </div>
}

Solution1/PresentationApp/Views/Shared/ProductDisplayPartial.cshtml
@model IEnumerable<ShoppingCart.Application.ViewModels.ProductViewModel>


@foreach (var p in Model)
{

    <div class="col-sm-6">

        <div class="card " style="width: 18rem;">

            <img src="@p.ImageUrl" class="card-img-top image" alt="image" crossorigin="anonymous">


            <div class="card-body">
                <h5 class="card-title">@p.Name</h5>
                <p class="card-text">€ @p.Price</p>

                <a href="Products/Details?id=@p.Id" class="btn btn-primary">Details</a>

                @if (User.IsInRole("Admin"))
                {
                    <a href="Products/Delete?id=@p.Id" class="btn btn-danger" onclick="return window.confirm('Are you sure?')">Delete</a>
                }



                @*@Html.ActionLink("Details", "Details", new { id = p.Id }, new {@class="btn btn-primary"})*@
            </div>
        </div>
    </div>
}

Solution1/PresentationApp/Views/Shared/SearchProductPartial.cshtml
<form class="row g-3" method="post" action="/Products/Search">
    <div class="col-auto">
        <label   >Search:</label>
    </div>
    <div class="col-auto">
        <input type="text" class="form-control" id="txtSearch" placeholder="Type keyword here"  name="keyword" >
    </div>
    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Search</button>
    </div>
</form>

Solution1/PresentationApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PresentationApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PresentationApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Support" asp-action="Contact">Contact Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

          @Html.Partial("PartialFeedbackView")

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PresentationApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>